### PR TITLE
Feature/qml rendering fixes

### PR DESCRIPTION
**Pull request by zeal18**
Plugin generation command moved into post install because of error: http://pastebin.com/17d6iTvN.
Set RPATH to VLCQtQml for searching libvlc and libvlccore inside VLCQtCore.framework.

There is still sample aspect ratio(sar) problem. Old solution is wrong: some channels stuck with sar == 0.0(for example: Euronews from my provider). I made other solution, but it requires VLC patching(patches: http://disk.karelia.pro/gLHGD1r/). I sent this patches to vlc-devel but it was rejected because of I have not enough English skill to give clear explanation.

I think STL containers and pointers must be replaced by Qt alternatives, VlcVideoStream must not depend on frame format(YUV now).

### CODE REVIEW

**Comment by ntadej** [comment]
Most of comments are OK. I will cherry pick most of them to my branch:
 - rpath fixes
 - track model registration
 - I will abstract frame type so more can be supported later on

For plugin generation, probably it just needs to depend on core so that it is found. Tests must not depend on install path. But to check rpaths, an app test is probably needed.

As for STL containers: there is no equivalent in Qt I think. Will investigate again.

**Comment by ntadej** [comment]
I made rendering type abstract.

As for STL containers: Why not use them? I need std::shared_ptr for reference count (Qt alternative doesn't have it), so probably it's also fine to have them for other things.

Closing this as it has been manually merged.

**Comment by SlySven** [comment]
FWIIW Qt is moving away from using its own functions in some areas and suggesting using STL equivalent replacements - e.g. `qSort(QList<T>)` is now depreciated and one is to use `std::sort(QList<T>::begin(), QList<T>::end())` since 5.4 or 5.5.  So Qt are not anti-STL.

**Comment by zeal18** [comment]
Qt has QSharedPointer class as alternative to std::shared_ptr

**Comment by ntadej** [comment]
QSharedPointer does not have reference count which is used to determine which frame is still in use.

**Comment by SlySven** [comment]
Would `QSharedDataPointer` be any use then?

**Comment by ntadej** [comment]
No, as frame would get copied when reference count goes above 1. Currently we reuse a pool of frames to avoid construction and deletion.

**Pull request closed without merging**
